Repository InteliJR/Imobiliaria, pull requests merged in 2024-11, with the labels that each got.

#169 Dockerizacao do Front + Docker Compose
  src/Auth-service/Dockerfile
  src/docker-compose.yml
  src/frontend/Dockerfile
Labels: feature, Infrastructure

#170 feat: axios + logica de pegar rotas + axios intercepter
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/pages/Landing.tsx
  src/frontend/src/pages/Login.tsx
  src/frontend/src/services/apiService.ts
  src/frontend/src/services/axiosConfig.ts
Labels: frontend

#173 FEAT | Not Found Page
  src/frontend/src/desktop/pages/NotFound.tsx
  src/frontend/src/main.tsx
  src/frontend/tailwind.config.js
Labels: frontend

#196 feat: Desenvolve página de edição de perfil e corrige a landing page
  src/frontend/package-lock.json
  src/frontend/src/desktop/App.tsx
  src/frontend/src/desktop/pages/AlterarSenha.tsx
  src/frontend/src/desktop/pages/Perfil.tsx
  src/frontend/src/index.css
  src/frontend/src/main.tsx
  src/frontend/src/mobile/App.tsx
  src/frontend/src/mobile/components/Botoes/Botao.tsx
  src/frontend/src/mobile/components/Botoes/BotaoAlterarSenha.tsx
  src/frontend/src/mobile/components/Form/FormField.tsx
  src/frontend/src/mobile/components/Landing/FeaturesSection.tsx
  src/frontend/src/mobile/components/ModalConfirmacao.tsx
  src/frontend/src/mobile/components/VisualizarItem.tsx
  src/frontend/src/mobile/components/Voltar.tsx
  src/frontend/src/mobile/pages/AlterarSenha.tsx
  src/frontend/src/mobile/pages/EditarPerfil.tsx
  src/frontend/src/mobile/pages/Landing.tsx
  src/frontend/src/mobile/pages/Perfil.tsx
  src/frontend/tailwind.config.js
Labels: frontend

#171 Feature/payment-notifications
  src/Payment-service/Dockerfile
  src/Payment-service/Layer.Application/Controllers/PaymentController.cs
  src/Payment-service/Layer.Application/Program.cs
  src/Payment-service/Layer.Domain/Interfaces/IEmailSender.cs
  src/Payment-service/Layer.Domain/Interfaces/IPaymentService.cs
  src/Payment-service/Layer.Services/Services/EmailSenderService.cs
  src/Payment-service/Layer.Services/Services/PaymentReminderService.cs
  src/Payment-service/Layer.Services/Services/PaymentService.cs
  src/Payment-service/Payment-service.sln
Labels: backend, feature

#204 FEATURE | Gateway
  src/Auth-service/Dockerfile
  src/Gateway/Dockerfile
  src/Gateway/DockerfileDev
  src/Gateway/nginx.conf
  src/Gateway/nginxDev.conf
  src/docker-compose.yml
Labels: backend, Infrastructure

#210 feat: adiciona servico de logs ao servico de pagamentos
  src/Payment-service/Dockerfile
  src/Payment-service/Layer.Application/Controllers/LogsController.cs
  src/Payment-service/Layer.Application/Controllers/PaymentController.cs
  src/Payment-service/Layer.Application/Layer.Application.csproj
  src/Payment-service/Layer.Application/Program.cs
  src/Payment-service/Layer.Domain/Entities/Log.cs
  src/Payment-service/Layer.Domain/Entities/MongoDbSettings.cs
  src/Payment-service/Layer.Domain/Enums/Roles.cs
  src/Payment-service/Layer.Domain/Layer.Domain.csproj
  src/Payment-service/Layer.Infrastructure/Database/ApplicationLog.cs
  src/Payment-service/Layer.Infrastructure/Layer.Infrastructure.csproj
Labels: backend, feature

#211 Colocando serviços de Property e Payment no gateway
  src/Auth-service/Layer.Application/Controllers/LocadorController.cs
  src/Gateway/nginx.conf
  src/Gateway/nginxDev.conf
  src/Payment-service/Dockerfile
  src/Payment-service/Layer.Application/Controllers/PaymentController.cs
  src/Payment-service/Layer.Application/Program.cs
  src/Payment-service/Layer.Domain/Entities/Payment.cs
  src/Property-service/.gitignore
  src/Property-service/Dockerfile
  src/Property-service/Layer.Application/Program.cs
  src/Property-service/Layer.Insfrastructure/Database/ApplicationDbContext.cs
  src/docker-compose.yml
Labels: backend, Infrastructure

#222 Cria instancia mongodb dockerizado e armazena logs do Auth-service
  src/docker-compose.yml
  src/logging-mongodb/Dockerfile
Labels: backend

#226 FEAT | Add forms pages
  src/frontend/src/desktop/components/Form/FormField.tsx
  src/frontend/src/desktop/pages/CreateProperty.tsx
  src/frontend/src/desktop/pages/CreateTicket.tsx
  src/frontend/src/desktop/pages/CreateUser.tsx
  src/frontend/src/desktop/pages/NotFound.tsx
  src/frontend/src/main.tsx
  src/frontend/src/mobile/pages/CreateProperty.tsx
  src/frontend/src/mobile/pages/CreateTicket.tsx
  src/frontend/src/mobile/pages/CreateUser.tsx
  src/frontend/tailwind.config.js
Labels: frontend

#229 Integrar tela de alterar senha
  src/Auth-service/Layer.Application/Controllers/UserController.cs
  src/Auth-service/Layer.Application/Program.cs
  src/Gateway/nginxDev.conf
  src/frontend/src/mobile/pages/AlterarSenha.tsx
  src/frontend/src/mobile/pages/Login.tsx
  src/frontend/src/services/axiosConfig.ts
Labels: frontend

#228 Feat: Adiciona o serviço de log no Property Service
  src/Property-service/Dockerfile
  src/Property-service/Layer.Application/Controllers/ChamadosController.cs
  src/Property-service/Layer.Application/Controllers/ContratosController.cs
  src/Property-service/Layer.Application/Controllers/ImoveisController.cs
  src/Property-service/Layer.Application/Program.cs
  src/Property-service/Layer.Application/appsettings.json
  src/docker-compose.yml
Labels: backend

#237 feat: implementa toast messages na aplicação
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/desktop/components/Chamados.tsx
  src/frontend/src/desktop/components/Dashboard.tsx
  src/frontend/src/desktop/components/FeatureSection.tsx
  src/frontend/src/desktop/components/Imoveis.tsx
  src/frontend/src/desktop/components/Usuarios.tsx
  src/frontend/src/desktop/components/WelcomeBanner.tsx
  src/frontend/src/desktop/pages/CreateProperty.tsx
  src/frontend/src/desktop/pages/CreateTicket.tsx
  src/frontend/src/desktop/pages/CreateUser.tsx
  src/frontend/src/desktop/pages/Landing.tsx
  src/frontend/src/desktop/pages/Login.tsx
  src/frontend/src/desktop/pages/VisualizarChamados.tsx
  src/frontend/src/desktop/pages/VisualizarImoveis.tsx
  src/frontend/src/desktop/pages/VisualizarUsuarios.tsx
  src/frontend/src/main.tsx
  src/frontend/src/mobile/pages/AlterarSenha.tsx
  src/frontend/src/mobile/pages/Chamado.tsx
  src/frontend/src/mobile/pages/CreateProperty.tsx
  src/frontend/src/mobile/pages/CreateTicket.tsx
  src/frontend/src/mobile/pages/CreateUser.tsx
  src/frontend/src/mobile/pages/Dashboard.tsx
  src/frontend/src/mobile/pages/EditarPerfil.tsx
  src/frontend/src/mobile/pages/Login.tsx
  src/frontend/src/mobile/pages/OutrosPerfis.tsx
  src/frontend/src/mobile/pages/Perfil.tsx
  src/frontend/src/mobile/pages/VisualizarChamados.tsx
  src/frontend/src/mobile/pages/VisualizarImoveis.tsx
  src/frontend/src/mobile/pages/VisualizarUsuarios.tsx
  src/frontend/src/utils/toastMessage.ts
Labels: feature, frontend
